//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceKullan.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kategori", Namespace="http://schemas.datacontract.org/2004/07/WCFSERVISI1")]
    [System.SerializableAttribute()]
    public partial class Kategori : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KATEGORI_ADIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KATEGORI_REFNOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KATEGORI_ADI {
            get {
                return this.KATEGORI_ADIField;
            }
            set {
                if ((object.ReferenceEquals(this.KATEGORI_ADIField, value) != true)) {
                    this.KATEGORI_ADIField = value;
                    this.RaisePropertyChanged("KATEGORI_ADI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KATEGORI_REFNO {
            get {
                return this.KATEGORI_REFNOField;
            }
            set {
                if ((this.KATEGORI_REFNOField.Equals(value) != true)) {
                    this.KATEGORI_REFNOField = value;
                    this.RaisePropertyChanged("KATEGORI_REFNO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceBlog")]
    public interface IServiceBlog {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBlog/GetAllKATEGORI", ReplyAction="http://tempuri.org/IServiceBlog/GetAllKATEGORIResponse")]
        WCFServiceKullan.ServiceReference1.Kategori[] GetAllKATEGORI();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBlog/GetAllKATEGORI", ReplyAction="http://tempuri.org/IServiceBlog/GetAllKATEGORIResponse")]
        System.Threading.Tasks.Task<WCFServiceKullan.ServiceReference1.Kategori[]> GetAllKATEGORIAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceBlogChannel : WCFServiceKullan.ServiceReference1.IServiceBlog, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBlogClient : System.ServiceModel.ClientBase<WCFServiceKullan.ServiceReference1.IServiceBlog>, WCFServiceKullan.ServiceReference1.IServiceBlog {
        
        public ServiceBlogClient() {
        }
        
        public ServiceBlogClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceBlogClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBlogClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBlogClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFServiceKullan.ServiceReference1.Kategori[] GetAllKATEGORI() {
            return base.Channel.GetAllKATEGORI();
        }
        
        public System.Threading.Tasks.Task<WCFServiceKullan.ServiceReference1.Kategori[]> GetAllKATEGORIAsync() {
            return base.Channel.GetAllKATEGORIAsync();
        }
    }
}
