//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFW
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PRATIKEntities : DbContext
    {
        public PRATIKEntities()
            : base("name=PRATIKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALT_KATEGORI> ALT_KATEGORI { get; set; }
        public virtual DbSet<FAT_DETAY> FAT_DETAY { get; set; }
        public virtual DbSet<FATURA> FATURAs { get; set; }
        public virtual DbSet<KATEGORI> KATEGORIs { get; set; }
        public virtual DbSet<KDV> KDVs { get; set; }
        public virtual DbSet<KULLANICI> KULLANICIs { get; set; }
        public virtual DbSet<MODUL> MODULs { get; set; }
        public virtual DbSet<MUSTERI> MUSTERIs { get; set; }
        public virtual DbSet<MUSTERI_HAREKET> MUSTERI_HAREKET { get; set; }
        public virtual DbSet<SIP_DETAY> SIP_DETAY { get; set; }
        public virtual DbSet<SIPARI> SIPARIS { get; set; }
        public virtual DbSet<URUN> URUNs { get; set; }
        public virtual DbSet<URUN_HAREKET> URUN_HAREKET { get; set; }
        public virtual DbSet<YETKI> YETKIs { get; set; }
    }
}
