//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFW
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODUL
    {
        public int MODUL_REFNO { get; set; }
        public string MODUL_ADI { get; set; }
    }
}
