//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFW
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUN_HAREKET
    {
        public int URUN_HAREKET_REFNO { get; set; }
        public Nullable<int> URUN_REFNO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string HAREKET_TIPI { get; set; }
        public Nullable<decimal> KDVSIZ_ALIS_FIYATI { get; set; }
        public Nullable<decimal> KDVSIZ_SATIS_FIYATI { get; set; }
        public Nullable<float> MIKTAR { get; set; }
        public string KAYNAK { get; set; }
        public Nullable<int> KAYNAK_REFNO { get; set; }
    }
}
