------------------------------------ INSERT TRIGGER ------------------------------------
CREATE TRIGGER INS_MUS_HAR ON MUS_HAR AFTER INSERT
AS
BEGIN
	UPDATE MUSTERI SET BAKIYE = BAKIYE + (inserted.BORC - inserted.ALACAK) FROM inserted
	WHERE MUSTERI.MUSTERI_REFNO = inserted.MUSTERI_REFNO
END

-- 2000 TL ye cep telefonu satýn alýyor

INSERT INTO MUS_HAR(MUSTERI_REFNO, TARIH, BORC, ALACAK)
VALUES(1, GETDATE(), 2000, 0)

SELECT * FROM MUSTERI
GO

------------------------------------ DELETE TRIGGER ------------------------------------
CREATE TRIGGER DEL_MUS_HAR ON MUS_HAR AFTER DELETE
AS
BEGIN
	UPDATE MUSTERI SET BAKIYE = BAKIYE - (deleted.BORC - deleted.ALACAK) FROM deleted
	WHERE MUSTERI.MUSTERI_REFNO = deleted.MUSTERI_REFNO
END 

DELETE FROM MUS_HAR
 
SELECT * FROM MUSTERI
GO

------------------------------------ UPDATE TRIGGER ------------------------------------
CREATE TRIGGER UPT_MUS_HAR ON MUS_HAR AFTER UPDATE
AS
BEGIN
	UPDATE MUSTERI SET BAKIYE = BAKIYE - (deleted.BORC - deleted.ALACAK) FROM deleted
	WHERE MUSTERI.MUSTERI_REFNO = deleted.MUSTERI_REFNO

	UPDATE MUSTERI SET BAKIYE = BAKIYE + (inserted.BORC - inserted.ALACAK) FROM inserted
	WHERE MUSTERI.MUSTERI_REFNO = inserted.MUSTERI_REFNO
END

INSERT INTO MUS_HAR(MUSTERI_REFNO, TARIH, BORC, ALACAK)
VALUES(1, GETDATE(), 2000, 0)

SELECT * FROM MUSTERI

INSERT INTO MUS_HAR(MUSTERI_REFNO, TARIH, BORC, ALACAK)
VALUES(1, GETDATE(), 1000, 0)

SELECT * FROM MUSTERI

UPDATE MUS_HAR SET BORC = 0, ALACAK = 1000 WHERE MUS_HAR_REFNO = 3

SELECT * FROM MUSTERI