-- Triggerlar 
-- INSERT UPDATE DELETE Trigger lar vardýr

-- INSERT TRIGGER
CREATE TRIGGER INS_KATILIMCI ON KATILIMCI AFTER INSERT
AS
BEGIN
	INSERT INTO GUNLUK(ISLEM_TIPI, TABLO_ADI, ACIKLAMA) SELECT 'INSERT', 'KATILIMCI', ADI_SOYADI + 'eklendi' FROM inserted
END
GO

INSERT INTO KATILIMCI(ADI_SOYADI, TC_KIMLIK, CEP_TEL, ADRES, EMAIL, ACIKLAMA)
VALUES('Ýsmail', '12345678905', '123345', 'Ankara', 'i@hotmail.com', 'isoaçýklama')
GO
-- --------------------------------------------------------------------------------------------------

-- UPDATE TRIGGER
CREATE TRIGGER UPD_KATILIMCI ON KATILIMCI AFTER UPDATE
AS
BEGIN
	INSERT INTO GUNLUK(ISLEM_TIPI, TABLO_ADI, ACIKLAMA) SELECT 'UPDATE', 'KATILIMCI', ADI_SOYADI + 'güncellendi' FROM deleted
END
GO

UPDATE KATILIMCI SET ADI_SOYADI = 'Kamil' WHERE KATILIMCI_REFNO = 4
GO
-- --------------------------------------------------------------------------------------------------

-- DELETE TRIGGER
CREATE TRIGGER DEL_KATILIMCI ON KATILIMCI AFTER DELETE
AS
BEGIN
	INSERT INTO GUNLUK(ISLEM_TIPI, TABLO_ADI, ACIKLAMA) SELECT 'DELETE', 'KATILIMCI', ADI_SOYADI + 'silindi' FROM deleted
END
GO

DELETE FROM KATILIMCI WHERE KATILIMCI_REFNO = 7

-- --------------------------------------------------------------------------------------------------
-- SINAV SORUSU
-- Varolan bir tablodan var olan bir tabloya kayýt ekleme (TOPLU INSERT)

-- INSERT INTO TABLO_ADI1 SELECT * FROM TABLO_ADI2
-- INSERT INTO YEDEK_TAKSIT(KATILIMCI_REFNO, BORC, ODENEN, TARIH) SELECT KATILIMCI_REFNO, BORC, ODENEN, TARIH FROM TAKSIT

-- Varolan bir tablodan yeni tablo oluþturma (YEDEKLEME)

-- SELECT * INTO TABLO_ADI2 FROM TABLO_ADI1

-- SELECT * INTO YEDEK_TAKSIT FROM TAKSIT
-- SELECT * FROM YEDEK_TAKSIT