/*SELECT TARIH, COUNT(*) FROM GUNLUK 
GROUP BY TARIH
GO*/

ALTER TRIGGER INS_GUNLUK ON GUNLUK AFTER INSERT
AS
BEGIN
	DECLARE @SAYI INT = 0
	DECLARE imlec CURSOR FOR SELECT TARIH FROM inserted
	DECLARE @TARIH date
	OPEN imlec
	FETCH NEXT FROM imlec INTO @TARIH
	WHILE(@@FETCH_STATUS = 0)
	BEGIN 
		SELECT @SAYI = COUNT(*) FROM HIT WHERE TARIH = @TARIH

		IF(@SAYI = 0)
		BEGIN
			INSERT INTO HIT(TARIH, HITSAYISI) VALUES(@TARIH, 1) 
		END
		ELSE
		BEGIN
			UPDATE HIT SET HITSAYISI = HITSAYISI + 1 WHERE TARIH = @TARIH
		END
		FETCH NEXT FROM imlec INTO @TARIH
	END
	CLOSE imlec
	DEALLOCATE imlec
END

-- GUNLUK'e otomatik ekleme yapan TSQL scripti
INSERT INTO GUNLUK(TARIH, SESSION_ID) VALUES(GETDATE(), 2)
SELECT * FROM HIT
GO

-- Otomatik 1000000 günlük ekleyen script
DECLARE @SAYI INT = 0
DECLARE @TARIH DATE
DECLARE @SESSION_ID INT
DECLARE @start DATE = '1980-01-01'
DECLARE @end DATE = '2000-12-31'

WHILE(@SAYI <= 1000000)
BEGIN
	SELECT @TARIH = DATEADD(DAY,ABS(CHECKSUM(NEWID())) % ( 1 + DATEDIFF(DAY,@start,@end)),@start)
	SET @SESSION_ID = RAND()*1000000
	INSERT INTO GUNLUK(TARIH, SESSION_ID) VALUES(@TARIH, @SESSION_ID) -- trigger ý tetikler
	SET @SAYI = @SAYI + 1
END


