/*SELECT TARIH, COUNT(*) FROM GUNLUK 
GROUP BY TARIH
GO*/

ALTER TRIGGER INS_GUNLUK ON GUNLUK AFTER INSERT
AS
BEGIN
	DECLARE @SAYI INT = 0
	DECLARE imlec CURSOR FOR SELECT TARIH FROM inserted
	DECLARE @TARIH date
	OPEN imlec
	FETCH NEXT FROM imlec INTO @TARIH
	WHILE(@@FETCH_STATUS = 0)
	BEGIN 
		SELECT @SAYI = COUNT(*) FROM HIT WHERE TARIH = @TARIH

		IF(@SAYI = 0)
		BEGIN
			INSERT INTO HIT(TARIH, HITSAYISI) VALUES(@TARIH, 1) 
		END
		ELSE
		BEGIN
			UPDATE HIT SET HITSAYISI = HITSAYISI + 1 WHERE TARIH = @TARIH
		END
		FETCH NEXT FROM imlec INTO @TARIH
	END
	CLOSE imlec
	DEALLOCATE imlec
END

-- GUNLUK'e otomatik ekleme yapan TSQL scripti
INSERT INTO GUNLUK(TARIH, SESSION_ID) VALUES(GETDATE(), 2)
SELECT * FROM HIT
GO

-- Otomatik 1000000 günlük ekleyen script
DECLARE @SAYI INT = 0
DECLARE @TARIH DATE
DECLARE @SESSION_ID INT
DECLARE @start DATE = '1980-01-01'
DECLARE @end DATE = '2000-12-31'

WHILE(@SAYI <= 1000000)
BEGIN
	SELECT @TARIH = DATEADD(DAY,ABS(CHECKSUM(NEWID())) % ( 1 + DATEDIFF(DAY,@start,@end)),@start)
	SET @SESSION_ID = RAND()*1000000
	INSERT INTO GUNLUK(TARIH, SESSION_ID) VALUES(@TARIH, @SESSION_ID) -- trigger ý tetikler
	SET @SAYI = @SAYI + 1
END
GO

-- Bugüne kadar toplam hit sayýsýný bulan fonksionu yazýnýz
CREATE FUNCTION fnc_TOPLAMHIT() RETURNS INT
AS
BEGIN
	DECLARE @TOPLAM INT
	SELECT @TOPLAM = SUM(HITSAYISI) FROM HIT
	RETURN @TOPLAM
END

SELECT dbo.fnc_TOPLAMHIT() AS TOPLAM_HIT
GO

-- Eksi 180 ile artý 180 arasýnda rastgele sayý üreten fonksiyon yazýnýz
ALTER VIEW Get_RAND
AS
SELECT -180+RAND()*360 AS MyRAND
GO

ALTER FUNCTION fnc_RANDOMSAYI() RETURNS INT
AS
BEGIN	
	RETURN (SELECT MyRAND FROM Get_RAND)
END
GO
SELECT dbo.fnc_RANDOMSAYI() AS RANDOM_SAYI
GO

-- Veri tabaný örneði alan yordam(procedure) yazýnýz
ALTER PROC usp_BACKUP(@DATABASE_NAME VARCHAR(100))
AS
BEGIN
	EXECUTE('BACKUP DATABASE ' + @DATABASE_NAME + ' TO DISK = E:\' + @DATABASE_NAME + '.bak');
END

EXEC usp_BACKUP 'TUCCAR'
GO
-- Ekrandan ; ile ayrýlmýþ þehir adlarýný
-- Adana;Kayseri;Niðde;Sivas;Ankara bir tablo þeklinde döndüren pro ve fonksiyonu yazýnýz

ALTER PROC usp_SPLIT(@YAZI VARCHAR(100))
AS
BEGIN
	DECLARE @YER1 INT = 0
	DECLARE @YER2 INT = 0
	DECLARE @BASLANGIC INT = 1
	DECLARE @SONUC VARCHAR(500) = ''
	SET @YER1 = CHARINDEX(';', @YAZI, @BASLANGIC)
	WHILE(@YER1 > 0)
	BEGIN
		SET @SONUC = @SONUC + ' SELECT ''' + SUBSTRING(@YAZI, @BASLANGIC, @YER1-@YER2-1) + ''' '
		SET @BASLANGIC = @YER1+1
		SET @YER2 = @YER1
		SET @YER1 = CHARINDEX(';', @YAZI, @BASLANGIC)
		IF(@YER1 > 0)
		BEGIN
			SET @SONUC = @SONUC + ' UNION ALL '
		END
	END
	EXECUTE(@SONUC)
END

EXEC usp_SPLIT 'Adana;Kayseri;Niðde;Sivas;Ankara'
