//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUTUPHANE
{
    using System;
    using System.Collections.Generic;
    
    public partial class KITAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KITAP()
        {
            this.ODUNC_KITAP = new HashSet<ODUNC_KITAP>();
        }
    
        public int KITAP_REFNO { get; set; }
        public string ADI { get; set; }
        public string ISBN { get; set; }
        public string YAZARI { get; set; }
        public System.DateTime BASIM_TARIHI { get; set; }
        public string YAYIN_EVI { get; set; }
        public string OZET { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ODUNC_KITAP> ODUNC_KITAP { get; set; }
    }
}
