//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUTUPHANE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KUTUPHANEEntities : DbContext
    {
        public KUTUPHANEEntities()
            : base("name=KUTUPHANEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KITAP> KITAPs { get; set; }
        public virtual DbSet<ODUNC_KITAP> ODUNC_KITAP { get; set; }
        public virtual DbSet<UYE> UYEs { get; set; }
    }
}
