//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUTUPHANE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODUNC_KITAP
    {
        public int ODUNC_KITAP_REFNO { get; set; }
        public int UYE_REFNO { get; set; }
        public int KITAP_REFNO { get; set; }
        public System.DateTime VERILIS_TARIHI { get; set; }
        public Nullable<System.DateTime> ALINIS_TARIHI { get; set; }
        public bool DURUMU { get; set; }
        public string ACIKLAMA { get; set; }
    
        public virtual KITAP KITAP { get; set; }
        public virtual UYE UYE { get; set; }
    }
}
