//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapHeaderWSKullan.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WSKATEGORISoap")]
    public interface WSKATEGORISoap {
        
        // CODEGEN: GetAllKATEGORIRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllKATEGORI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapHeaderWSKullan.ServiceReference2.GetAllKATEGORIResponse GetAllKATEGORI(SoapHeaderWSKullan.ServiceReference2.GetAllKATEGORIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllKATEGORI", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapHeaderWSKullan.ServiceReference2.GetAllKATEGORIResponse> GetAllKATEGORIAsync(SoapHeaderWSKullan.ServiceReference2.GetAllKATEGORIRequest request);
        
        // CODEGEN: GetKATEGORIRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKATEGORI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapHeaderWSKullan.ServiceReference2.GetKATEGORIResponse GetKATEGORI(SoapHeaderWSKullan.ServiceReference2.GetKATEGORIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKATEGORI", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapHeaderWSKullan.ServiceReference2.GetKATEGORIResponse> GetKATEGORIAsync(SoapHeaderWSKullan.ServiceReference2.GetKATEGORIRequest request);
        
        // CODEGEN: SaveKATEGORIRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveKATEGORI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapHeaderWSKullan.ServiceReference2.SaveKATEGORIResponse SaveKATEGORI(SoapHeaderWSKullan.ServiceReference2.SaveKATEGORIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveKATEGORI", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapHeaderWSKullan.ServiceReference2.SaveKATEGORIResponse> SaveKATEGORIAsync(SoapHeaderWSKullan.ServiceReference2.SaveKATEGORIRequest request);
        
        // CODEGEN: UpdateKATEGORIRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateKATEGORI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapHeaderWSKullan.ServiceReference2.UpdateKATEGORIResponse UpdateKATEGORI(SoapHeaderWSKullan.ServiceReference2.UpdateKATEGORIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateKATEGORI", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapHeaderWSKullan.ServiceReference2.UpdateKATEGORIResponse> UpdateKATEGORIAsync(SoapHeaderWSKullan.ServiceReference2.UpdateKATEGORIRequest request);
        
        // CODEGEN: DeleteKATEGORIRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteKATEGORI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapHeaderWSKullan.ServiceReference2.DeleteKATEGORIResponse DeleteKATEGORI(SoapHeaderWSKullan.ServiceReference2.DeleteKATEGORIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteKATEGORI", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapHeaderWSKullan.ServiceReference2.DeleteKATEGORIResponse> DeleteKATEGORIAsync(SoapHeaderWSKullan.ServiceReference2.DeleteKATEGORIRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GirisDenetle : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string prm1Field;
        
        private string prm2Field;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string prm1 {
            get {
                return this.prm1Field;
            }
            set {
                this.prm1Field = value;
                this.RaisePropertyChanged("prm1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string prm2 {
            get {
                return this.prm2Field;
            }
            set {
                this.prm2Field = value;
                this.RaisePropertyChanged("prm2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KATEGORI : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int kATEGORI_REFNOField;
        
        private string kATEGORI_ADIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int KATEGORI_REFNO {
            get {
                return this.kATEGORI_REFNOField;
            }
            set {
                this.kATEGORI_REFNOField = value;
                this.RaisePropertyChanged("KATEGORI_REFNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string KATEGORI_ADI {
            get {
                return this.kATEGORI_ADIField;
            }
            set {
                this.kATEGORI_ADIField = value;
                this.RaisePropertyChanged("KATEGORI_ADI");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllKATEGORI", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllKATEGORIRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SoapHeaderWSKullan.ServiceReference2.GirisDenetle GirisDenetle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string arama;
        
        public GetAllKATEGORIRequest() {
        }
        
        public GetAllKATEGORIRequest(SoapHeaderWSKullan.ServiceReference2.GirisDenetle GirisDenetle, string arama) {
            this.GirisDenetle = GirisDenetle;
            this.arama = arama;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllKATEGORIResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllKATEGORIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SoapHeaderWSKullan.ServiceReference2.KATEGORI[] GetAllKATEGORIResult;
        
        public GetAllKATEGORIResponse() {
        }
        
        public GetAllKATEGORIResponse(SoapHeaderWSKullan.ServiceReference2.KATEGORI[] GetAllKATEGORIResult) {
            this.GetAllKATEGORIResult = GetAllKATEGORIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKATEGORI", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetKATEGORIRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SoapHeaderWSKullan.ServiceReference2.GirisDenetle GirisDenetle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public GetKATEGORIRequest() {
        }
        
        public GetKATEGORIRequest(SoapHeaderWSKullan.ServiceReference2.GirisDenetle GirisDenetle, int id) {
            this.GirisDenetle = GirisDenetle;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKATEGORIResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetKATEGORIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SoapHeaderWSKullan.ServiceReference2.KATEGORI GetKATEGORIResult;
        
        public GetKATEGORIResponse() {
        }
        
        public GetKATEGORIResponse(SoapHeaderWSKullan.ServiceReference2.KATEGORI GetKATEGORIResult) {
            this.GetKATEGORIResult = GetKATEGORIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveKATEGORI", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveKATEGORIRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SoapHeaderWSKullan.ServiceReference2.GirisDenetle GirisDenetle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SoapHeaderWSKullan.ServiceReference2.KATEGORI k;
        
        public SaveKATEGORIRequest() {
        }
        
        public SaveKATEGORIRequest(SoapHeaderWSKullan.ServiceReference2.GirisDenetle GirisDenetle, SoapHeaderWSKullan.ServiceReference2.KATEGORI k) {
            this.GirisDenetle = GirisDenetle;
            this.k = k;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveKATEGORIResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveKATEGORIResponse {
        
        public SaveKATEGORIResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateKATEGORI", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateKATEGORIRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SoapHeaderWSKullan.ServiceReference2.GirisDenetle GirisDenetle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SoapHeaderWSKullan.ServiceReference2.KATEGORI k;
        
        public UpdateKATEGORIRequest() {
        }
        
        public UpdateKATEGORIRequest(SoapHeaderWSKullan.ServiceReference2.GirisDenetle GirisDenetle, SoapHeaderWSKullan.ServiceReference2.KATEGORI k) {
            this.GirisDenetle = GirisDenetle;
            this.k = k;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateKATEGORIResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateKATEGORIResponse {
        
        public UpdateKATEGORIResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteKATEGORI", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteKATEGORIRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SoapHeaderWSKullan.ServiceReference2.GirisDenetle GirisDenetle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public DeleteKATEGORIRequest() {
        }
        
        public DeleteKATEGORIRequest(SoapHeaderWSKullan.ServiceReference2.GirisDenetle GirisDenetle, int id) {
            this.GirisDenetle = GirisDenetle;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteKATEGORIResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteKATEGORIResponse {
        
        public DeleteKATEGORIResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSKATEGORISoapChannel : SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSKATEGORISoapClient : System.ServiceModel.ClientBase<SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap>, SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap {
        
        public WSKATEGORISoapClient() {
        }
        
        public WSKATEGORISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSKATEGORISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSKATEGORISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSKATEGORISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapHeaderWSKullan.ServiceReference2.GetAllKATEGORIResponse SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap.GetAllKATEGORI(SoapHeaderWSKullan.ServiceReference2.GetAllKATEGORIRequest request) {
            return base.Channel.GetAllKATEGORI(request);
        }
        
        public SoapHeaderWSKullan.ServiceReference2.KATEGORI[] GetAllKATEGORI(SoapHeaderWSKullan.ServiceReference2.GirisDenetle GirisDenetle, string arama) {
            SoapHeaderWSKullan.ServiceReference2.GetAllKATEGORIRequest inValue = new SoapHeaderWSKullan.ServiceReference2.GetAllKATEGORIRequest();
            inValue.GirisDenetle = GirisDenetle;
            inValue.arama = arama;
            SoapHeaderWSKullan.ServiceReference2.GetAllKATEGORIResponse retVal = ((SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap)(this)).GetAllKATEGORI(inValue);
            return retVal.GetAllKATEGORIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapHeaderWSKullan.ServiceReference2.GetAllKATEGORIResponse> SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap.GetAllKATEGORIAsync(SoapHeaderWSKullan.ServiceReference2.GetAllKATEGORIRequest request) {
            return base.Channel.GetAllKATEGORIAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapHeaderWSKullan.ServiceReference2.GetAllKATEGORIResponse> GetAllKATEGORIAsync(SoapHeaderWSKullan.ServiceReference2.GirisDenetle GirisDenetle, string arama) {
            SoapHeaderWSKullan.ServiceReference2.GetAllKATEGORIRequest inValue = new SoapHeaderWSKullan.ServiceReference2.GetAllKATEGORIRequest();
            inValue.GirisDenetle = GirisDenetle;
            inValue.arama = arama;
            return ((SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap)(this)).GetAllKATEGORIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapHeaderWSKullan.ServiceReference2.GetKATEGORIResponse SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap.GetKATEGORI(SoapHeaderWSKullan.ServiceReference2.GetKATEGORIRequest request) {
            return base.Channel.GetKATEGORI(request);
        }
        
        public SoapHeaderWSKullan.ServiceReference2.KATEGORI GetKATEGORI(SoapHeaderWSKullan.ServiceReference2.GirisDenetle GirisDenetle, int id) {
            SoapHeaderWSKullan.ServiceReference2.GetKATEGORIRequest inValue = new SoapHeaderWSKullan.ServiceReference2.GetKATEGORIRequest();
            inValue.GirisDenetle = GirisDenetle;
            inValue.id = id;
            SoapHeaderWSKullan.ServiceReference2.GetKATEGORIResponse retVal = ((SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap)(this)).GetKATEGORI(inValue);
            return retVal.GetKATEGORIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapHeaderWSKullan.ServiceReference2.GetKATEGORIResponse> SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap.GetKATEGORIAsync(SoapHeaderWSKullan.ServiceReference2.GetKATEGORIRequest request) {
            return base.Channel.GetKATEGORIAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapHeaderWSKullan.ServiceReference2.GetKATEGORIResponse> GetKATEGORIAsync(SoapHeaderWSKullan.ServiceReference2.GirisDenetle GirisDenetle, int id) {
            SoapHeaderWSKullan.ServiceReference2.GetKATEGORIRequest inValue = new SoapHeaderWSKullan.ServiceReference2.GetKATEGORIRequest();
            inValue.GirisDenetle = GirisDenetle;
            inValue.id = id;
            return ((SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap)(this)).GetKATEGORIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapHeaderWSKullan.ServiceReference2.SaveKATEGORIResponse SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap.SaveKATEGORI(SoapHeaderWSKullan.ServiceReference2.SaveKATEGORIRequest request) {
            return base.Channel.SaveKATEGORI(request);
        }
        
        public void SaveKATEGORI(SoapHeaderWSKullan.ServiceReference2.GirisDenetle GirisDenetle, SoapHeaderWSKullan.ServiceReference2.KATEGORI k) {
            SoapHeaderWSKullan.ServiceReference2.SaveKATEGORIRequest inValue = new SoapHeaderWSKullan.ServiceReference2.SaveKATEGORIRequest();
            inValue.GirisDenetle = GirisDenetle;
            inValue.k = k;
            SoapHeaderWSKullan.ServiceReference2.SaveKATEGORIResponse retVal = ((SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap)(this)).SaveKATEGORI(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapHeaderWSKullan.ServiceReference2.SaveKATEGORIResponse> SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap.SaveKATEGORIAsync(SoapHeaderWSKullan.ServiceReference2.SaveKATEGORIRequest request) {
            return base.Channel.SaveKATEGORIAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapHeaderWSKullan.ServiceReference2.SaveKATEGORIResponse> SaveKATEGORIAsync(SoapHeaderWSKullan.ServiceReference2.GirisDenetle GirisDenetle, SoapHeaderWSKullan.ServiceReference2.KATEGORI k) {
            SoapHeaderWSKullan.ServiceReference2.SaveKATEGORIRequest inValue = new SoapHeaderWSKullan.ServiceReference2.SaveKATEGORIRequest();
            inValue.GirisDenetle = GirisDenetle;
            inValue.k = k;
            return ((SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap)(this)).SaveKATEGORIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapHeaderWSKullan.ServiceReference2.UpdateKATEGORIResponse SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap.UpdateKATEGORI(SoapHeaderWSKullan.ServiceReference2.UpdateKATEGORIRequest request) {
            return base.Channel.UpdateKATEGORI(request);
        }
        
        public void UpdateKATEGORI(SoapHeaderWSKullan.ServiceReference2.GirisDenetle GirisDenetle, SoapHeaderWSKullan.ServiceReference2.KATEGORI k) {
            SoapHeaderWSKullan.ServiceReference2.UpdateKATEGORIRequest inValue = new SoapHeaderWSKullan.ServiceReference2.UpdateKATEGORIRequest();
            inValue.GirisDenetle = GirisDenetle;
            inValue.k = k;
            SoapHeaderWSKullan.ServiceReference2.UpdateKATEGORIResponse retVal = ((SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap)(this)).UpdateKATEGORI(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapHeaderWSKullan.ServiceReference2.UpdateKATEGORIResponse> SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap.UpdateKATEGORIAsync(SoapHeaderWSKullan.ServiceReference2.UpdateKATEGORIRequest request) {
            return base.Channel.UpdateKATEGORIAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapHeaderWSKullan.ServiceReference2.UpdateKATEGORIResponse> UpdateKATEGORIAsync(SoapHeaderWSKullan.ServiceReference2.GirisDenetle GirisDenetle, SoapHeaderWSKullan.ServiceReference2.KATEGORI k) {
            SoapHeaderWSKullan.ServiceReference2.UpdateKATEGORIRequest inValue = new SoapHeaderWSKullan.ServiceReference2.UpdateKATEGORIRequest();
            inValue.GirisDenetle = GirisDenetle;
            inValue.k = k;
            return ((SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap)(this)).UpdateKATEGORIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapHeaderWSKullan.ServiceReference2.DeleteKATEGORIResponse SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap.DeleteKATEGORI(SoapHeaderWSKullan.ServiceReference2.DeleteKATEGORIRequest request) {
            return base.Channel.DeleteKATEGORI(request);
        }
        
        public void DeleteKATEGORI(SoapHeaderWSKullan.ServiceReference2.GirisDenetle GirisDenetle, int id) {
            SoapHeaderWSKullan.ServiceReference2.DeleteKATEGORIRequest inValue = new SoapHeaderWSKullan.ServiceReference2.DeleteKATEGORIRequest();
            inValue.GirisDenetle = GirisDenetle;
            inValue.id = id;
            SoapHeaderWSKullan.ServiceReference2.DeleteKATEGORIResponse retVal = ((SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap)(this)).DeleteKATEGORI(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapHeaderWSKullan.ServiceReference2.DeleteKATEGORIResponse> SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap.DeleteKATEGORIAsync(SoapHeaderWSKullan.ServiceReference2.DeleteKATEGORIRequest request) {
            return base.Channel.DeleteKATEGORIAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapHeaderWSKullan.ServiceReference2.DeleteKATEGORIResponse> DeleteKATEGORIAsync(SoapHeaderWSKullan.ServiceReference2.GirisDenetle GirisDenetle, int id) {
            SoapHeaderWSKullan.ServiceReference2.DeleteKATEGORIRequest inValue = new SoapHeaderWSKullan.ServiceReference2.DeleteKATEGORIRequest();
            inValue.GirisDenetle = GirisDenetle;
            inValue.id = id;
            return ((SoapHeaderWSKullan.ServiceReference2.WSKATEGORISoap)(this)).DeleteKATEGORIAsync(inValue);
        }
    }
}
