//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFTest2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kategori", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Kategori : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KATEGORI_ADIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KATEGORI_REFNOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KATEGORI_ADI {
            get {
                return this.KATEGORI_ADIField;
            }
            set {
                if ((object.ReferenceEquals(this.KATEGORI_ADIField, value) != true)) {
                    this.KATEGORI_ADIField = value;
                    this.RaisePropertyChanged("KATEGORI_ADI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KATEGORI_REFNO {
            get {
                return this.KATEGORI_REFNOField;
            }
            set {
                if ((this.KATEGORI_REFNOField.Equals(value) != true)) {
                    this.KATEGORI_REFNOField = value;
                    this.RaisePropertyChanged("KATEGORI_REFNO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWSKategori")]
    public interface IWSKategori {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSKategori/GetAllKATEGORI", ReplyAction="http://tempuri.org/IWSKategori/GetAllKATEGORIResponse")]
        WCFTest2.ServiceReference1.Kategori[] GetAllKATEGORI();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSKategori/GetAllKATEGORI", ReplyAction="http://tempuri.org/IWSKategori/GetAllKATEGORIResponse")]
        System.Threading.Tasks.Task<WCFTest2.ServiceReference1.Kategori[]> GetAllKATEGORIAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSKategori/GetKATEGORI", ReplyAction="http://tempuri.org/IWSKategori/GetKATEGORIResponse")]
        WCFTest2.ServiceReference1.Kategori GetKATEGORI(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSKategori/GetKATEGORI", ReplyAction="http://tempuri.org/IWSKategori/GetKATEGORIResponse")]
        System.Threading.Tasks.Task<WCFTest2.ServiceReference1.Kategori> GetKATEGORIAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSKategori/Save", ReplyAction="http://tempuri.org/IWSKategori/SaveResponse")]
        void Save(WCFTest2.ServiceReference1.Kategori kategori);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSKategori/Save", ReplyAction="http://tempuri.org/IWSKategori/SaveResponse")]
        System.Threading.Tasks.Task SaveAsync(WCFTest2.ServiceReference1.Kategori kategori);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSKategori/Update", ReplyAction="http://tempuri.org/IWSKategori/UpdateResponse")]
        void Update(WCFTest2.ServiceReference1.Kategori kategori);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSKategori/Update", ReplyAction="http://tempuri.org/IWSKategori/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(WCFTest2.ServiceReference1.Kategori kategori);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSKategori/Delete", ReplyAction="http://tempuri.org/IWSKategori/DeleteResponse")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSKategori/Delete", ReplyAction="http://tempuri.org/IWSKategori/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSKategoriChannel : WCFTest2.ServiceReference1.IWSKategori, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSKategoriClient : System.ServiceModel.ClientBase<WCFTest2.ServiceReference1.IWSKategori>, WCFTest2.ServiceReference1.IWSKategori {
        
        public WSKategoriClient() {
        }
        
        public WSKategoriClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSKategoriClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSKategoriClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSKategoriClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFTest2.ServiceReference1.Kategori[] GetAllKATEGORI() {
            return base.Channel.GetAllKATEGORI();
        }
        
        public System.Threading.Tasks.Task<WCFTest2.ServiceReference1.Kategori[]> GetAllKATEGORIAsync() {
            return base.Channel.GetAllKATEGORIAsync();
        }
        
        public WCFTest2.ServiceReference1.Kategori GetKATEGORI(int id) {
            return base.Channel.GetKATEGORI(id);
        }
        
        public System.Threading.Tasks.Task<WCFTest2.ServiceReference1.Kategori> GetKATEGORIAsync(int id) {
            return base.Channel.GetKATEGORIAsync(id);
        }
        
        public void Save(WCFTest2.ServiceReference1.Kategori kategori) {
            base.Channel.Save(kategori);
        }
        
        public System.Threading.Tasks.Task SaveAsync(WCFTest2.ServiceReference1.Kategori kategori) {
            return base.Channel.SaveAsync(kategori);
        }
        
        public void Update(WCFTest2.ServiceReference1.Kategori kategori) {
            base.Channel.Update(kategori);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(WCFTest2.ServiceReference1.Kategori kategori) {
            return base.Channel.UpdateAsync(kategori);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
