//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIRMA_ASPX
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJE
    {
        public int PROJE_REFNO { get; set; }
        public string PROJE_ADI { get; set; }
        public string RESIM { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
