//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIRMA_ASPX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLIDER
    {
        public int SLIDER_REFNO { get; set; }
        public string BASLIK { get; set; }
        public string LINK { get; set; }
        public string RESIM { get; set; }
        public bool DURUMU { get; set; }
    }
}
