//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIRMA_ASPX
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunler
    {
        public string ACIKLAMA { get; set; }
        public bool DURUMU { get; set; }
        public decimal FIYATI { get; set; }
        public int KDV_ORANI { get; set; }
        public int URUN_REFNO { get; set; }
        public string RESIM1 { get; set; }
        public string RESIM2 { get; set; }
        public string RESIM3 { get; set; }
        public string RESIM4 { get; set; }
        public string URUN_ADI { get; set; }
        public int KATEGORI_REFNO { get; set; }
        public string KATEGORI_ADI { get; set; }
        public int MARKA_REFNO { get; set; }
        public string MARKA_ADI { get; set; }
    }
}
