//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUNLUK
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICI
    {
        public int KULLANICI_REFNO { get; set; }
        public string KULLANICI_ADI { get; set; }
        public string PAROLA { get; set; }
        public bool DURUMU { get; set; }
    }
}
