//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUNLUK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BLOGEntities : DbContext
    {
        public BLOGEntities()
            : base("name=BLOGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KATEGORI> KATEGORI { get; set; }
        public virtual DbSet<KULLANICI> KULLANICI { get; set; }
        public virtual DbSet<SAYFA> SAYFA { get; set; }
        public virtual DbSet<YAZI> YAZI { get; set; }
        public virtual DbSet<YORUM> YORUM { get; set; }
    }
}
