//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUNLUK
{
    using System;
    using System.Collections.Generic;
    
    public partial class YAZI
    {
        public int YAZI_REFNO { get; set; }
        public string BASLIK { get; set; }
        public string ICERIK { get; set; }
        public System.DateTime TARIH { get; set; }
        public bool DURUMU { get; set; }
        public int KATEGORI_REFNO { get; set; }
        public int TIKLAMA_SAYISI { get; set; }
        public string OZET { get; set; }
        public string RESIM { get; set; }
    }
}
