//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUNLUK
{
    using System;
    using System.Collections.Generic;
    
    public partial class YORUM
    {
        public int YORUM_REFNO { get; set; }
        public int YAZI_REFNO { get; set; }
        public string MAIL { get; set; }
        public string ADI_SOYADI { get; set; }
        public bool DURUMU { get; set; }
        public System.DateTime TARIH { get; set; }
        public string IP { get; set; }
        public string YORUM_ICERIK { get; set; }
    }
}
