//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapHeaderWSKullan.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="URUN", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class URUN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int URUN_REFNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STOK_KODUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URUN_ADIField;
        
        private decimal FIYATIField;
        
        private int DOVIZ_REFNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RESIMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DETAYField;
        
        private decimal INDIRIMLI_FIYATField;
        
        private bool INDIRIM_DURUMUField;
        
        private int TIKLAMA_SAYISIField;
        
        private int KDV_REFNOField;
        
        private int ALT_KATEGORI_REFNOField;
        
        private bool SPOT_URUNField;
        
        private int MARKA_REFNOField;
        
        private int ADETField;
        
        private bool DURUMUField;
        
        private bool FIYAT_LISTESIField;
        
        private System.Nullable<System.DateTime> KAYIT_TARIHIField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int URUN_REFNO {
            get {
                return this.URUN_REFNOField;
            }
            set {
                if ((this.URUN_REFNOField.Equals(value) != true)) {
                    this.URUN_REFNOField = value;
                    this.RaisePropertyChanged("URUN_REFNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string STOK_KODU {
            get {
                return this.STOK_KODUField;
            }
            set {
                if ((object.ReferenceEquals(this.STOK_KODUField, value) != true)) {
                    this.STOK_KODUField = value;
                    this.RaisePropertyChanged("STOK_KODU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string URUN_ADI {
            get {
                return this.URUN_ADIField;
            }
            set {
                if ((object.ReferenceEquals(this.URUN_ADIField, value) != true)) {
                    this.URUN_ADIField = value;
                    this.RaisePropertyChanged("URUN_ADI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal FIYATI {
            get {
                return this.FIYATIField;
            }
            set {
                if ((this.FIYATIField.Equals(value) != true)) {
                    this.FIYATIField = value;
                    this.RaisePropertyChanged("FIYATI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int DOVIZ_REFNO {
            get {
                return this.DOVIZ_REFNOField;
            }
            set {
                if ((this.DOVIZ_REFNOField.Equals(value) != true)) {
                    this.DOVIZ_REFNOField = value;
                    this.RaisePropertyChanged("DOVIZ_REFNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string RESIM {
            get {
                return this.RESIMField;
            }
            set {
                if ((object.ReferenceEquals(this.RESIMField, value) != true)) {
                    this.RESIMField = value;
                    this.RaisePropertyChanged("RESIM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string DETAY {
            get {
                return this.DETAYField;
            }
            set {
                if ((object.ReferenceEquals(this.DETAYField, value) != true)) {
                    this.DETAYField = value;
                    this.RaisePropertyChanged("DETAY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal INDIRIMLI_FIYAT {
            get {
                return this.INDIRIMLI_FIYATField;
            }
            set {
                if ((this.INDIRIMLI_FIYATField.Equals(value) != true)) {
                    this.INDIRIMLI_FIYATField = value;
                    this.RaisePropertyChanged("INDIRIMLI_FIYAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool INDIRIM_DURUMU {
            get {
                return this.INDIRIM_DURUMUField;
            }
            set {
                if ((this.INDIRIM_DURUMUField.Equals(value) != true)) {
                    this.INDIRIM_DURUMUField = value;
                    this.RaisePropertyChanged("INDIRIM_DURUMU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int TIKLAMA_SAYISI {
            get {
                return this.TIKLAMA_SAYISIField;
            }
            set {
                if ((this.TIKLAMA_SAYISIField.Equals(value) != true)) {
                    this.TIKLAMA_SAYISIField = value;
                    this.RaisePropertyChanged("TIKLAMA_SAYISI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int KDV_REFNO {
            get {
                return this.KDV_REFNOField;
            }
            set {
                if ((this.KDV_REFNOField.Equals(value) != true)) {
                    this.KDV_REFNOField = value;
                    this.RaisePropertyChanged("KDV_REFNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int ALT_KATEGORI_REFNO {
            get {
                return this.ALT_KATEGORI_REFNOField;
            }
            set {
                if ((this.ALT_KATEGORI_REFNOField.Equals(value) != true)) {
                    this.ALT_KATEGORI_REFNOField = value;
                    this.RaisePropertyChanged("ALT_KATEGORI_REFNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool SPOT_URUN {
            get {
                return this.SPOT_URUNField;
            }
            set {
                if ((this.SPOT_URUNField.Equals(value) != true)) {
                    this.SPOT_URUNField = value;
                    this.RaisePropertyChanged("SPOT_URUN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int MARKA_REFNO {
            get {
                return this.MARKA_REFNOField;
            }
            set {
                if ((this.MARKA_REFNOField.Equals(value) != true)) {
                    this.MARKA_REFNOField = value;
                    this.RaisePropertyChanged("MARKA_REFNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public int ADET {
            get {
                return this.ADETField;
            }
            set {
                if ((this.ADETField.Equals(value) != true)) {
                    this.ADETField = value;
                    this.RaisePropertyChanged("ADET");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public bool DURUMU {
            get {
                return this.DURUMUField;
            }
            set {
                if ((this.DURUMUField.Equals(value) != true)) {
                    this.DURUMUField = value;
                    this.RaisePropertyChanged("DURUMU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public bool FIYAT_LISTESI {
            get {
                return this.FIYAT_LISTESIField;
            }
            set {
                if ((this.FIYAT_LISTESIField.Equals(value) != true)) {
                    this.FIYAT_LISTESIField = value;
                    this.RaisePropertyChanged("FIYAT_LISTESI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.Nullable<System.DateTime> KAYIT_TARIHI {
            get {
                return this.KAYIT_TARIHIField;
            }
            set {
                if ((this.KAYIT_TARIHIField.Equals(value) != true)) {
                    this.KAYIT_TARIHIField = value;
                    this.RaisePropertyChanged("KAYIT_TARIHI");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: http://tempuri.org/ ad alanındaki HelloWorldResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SoapHeaderWSKullan.ServiceReference1.HelloWorldResponse HelloWorld(SoapHeaderWSKullan.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapHeaderWSKullan.ServiceReference1.HelloWorldResponse> HelloWorldAsync(SoapHeaderWSKullan.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki GetAllUrunsResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUruns", ReplyAction="*")]
        SoapHeaderWSKullan.ServiceReference1.GetAllUrunsResponse GetAllUruns(SoapHeaderWSKullan.ServiceReference1.GetAllUrunsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUruns", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapHeaderWSKullan.ServiceReference1.GetAllUrunsResponse> GetAllUrunsAsync(SoapHeaderWSKullan.ServiceReference1.GetAllUrunsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SoapHeaderWSKullan.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SoapHeaderWSKullan.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SoapHeaderWSKullan.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SoapHeaderWSKullan.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUrunsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUruns", Namespace="http://tempuri.org/", Order=0)]
        public SoapHeaderWSKullan.ServiceReference1.GetAllUrunsRequestBody Body;
        
        public GetAllUrunsRequest() {
        }
        
        public GetAllUrunsRequest(SoapHeaderWSKullan.ServiceReference1.GetAllUrunsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllUrunsRequestBody {
        
        public GetAllUrunsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUrunsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUrunsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SoapHeaderWSKullan.ServiceReference1.GetAllUrunsResponseBody Body;
        
        public GetAllUrunsResponse() {
        }
        
        public GetAllUrunsResponse(SoapHeaderWSKullan.ServiceReference1.GetAllUrunsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllUrunsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoapHeaderWSKullan.ServiceReference1.URUN[] GetAllUrunsResult;
        
        public GetAllUrunsResponseBody() {
        }
        
        public GetAllUrunsResponseBody(SoapHeaderWSKullan.ServiceReference1.URUN[] GetAllUrunsResult) {
            this.GetAllUrunsResult = GetAllUrunsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : SoapHeaderWSKullan.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<SoapHeaderWSKullan.ServiceReference1.WebService1Soap>, SoapHeaderWSKullan.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapHeaderWSKullan.ServiceReference1.HelloWorldResponse SoapHeaderWSKullan.ServiceReference1.WebService1Soap.HelloWorld(SoapHeaderWSKullan.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SoapHeaderWSKullan.ServiceReference1.HelloWorldRequest inValue = new SoapHeaderWSKullan.ServiceReference1.HelloWorldRequest();
            inValue.Body = new SoapHeaderWSKullan.ServiceReference1.HelloWorldRequestBody();
            SoapHeaderWSKullan.ServiceReference1.HelloWorldResponse retVal = ((SoapHeaderWSKullan.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapHeaderWSKullan.ServiceReference1.HelloWorldResponse> SoapHeaderWSKullan.ServiceReference1.WebService1Soap.HelloWorldAsync(SoapHeaderWSKullan.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapHeaderWSKullan.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            SoapHeaderWSKullan.ServiceReference1.HelloWorldRequest inValue = new SoapHeaderWSKullan.ServiceReference1.HelloWorldRequest();
            inValue.Body = new SoapHeaderWSKullan.ServiceReference1.HelloWorldRequestBody();
            return ((SoapHeaderWSKullan.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapHeaderWSKullan.ServiceReference1.GetAllUrunsResponse SoapHeaderWSKullan.ServiceReference1.WebService1Soap.GetAllUruns(SoapHeaderWSKullan.ServiceReference1.GetAllUrunsRequest request) {
            return base.Channel.GetAllUruns(request);
        }
        
        public SoapHeaderWSKullan.ServiceReference1.URUN[] GetAllUruns() {
            SoapHeaderWSKullan.ServiceReference1.GetAllUrunsRequest inValue = new SoapHeaderWSKullan.ServiceReference1.GetAllUrunsRequest();
            inValue.Body = new SoapHeaderWSKullan.ServiceReference1.GetAllUrunsRequestBody();
            SoapHeaderWSKullan.ServiceReference1.GetAllUrunsResponse retVal = ((SoapHeaderWSKullan.ServiceReference1.WebService1Soap)(this)).GetAllUruns(inValue);
            return retVal.Body.GetAllUrunsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapHeaderWSKullan.ServiceReference1.GetAllUrunsResponse> SoapHeaderWSKullan.ServiceReference1.WebService1Soap.GetAllUrunsAsync(SoapHeaderWSKullan.ServiceReference1.GetAllUrunsRequest request) {
            return base.Channel.GetAllUrunsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapHeaderWSKullan.ServiceReference1.GetAllUrunsResponse> GetAllUrunsAsync() {
            SoapHeaderWSKullan.ServiceReference1.GetAllUrunsRequest inValue = new SoapHeaderWSKullan.ServiceReference1.GetAllUrunsRequest();
            inValue.Body = new SoapHeaderWSKullan.ServiceReference1.GetAllUrunsRequestBody();
            return ((SoapHeaderWSKullan.ServiceReference1.WebService1Soap)(this)).GetAllUrunsAsync(inValue);
        }
    }
}
