//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_OGRENIYORUM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALT_KATEGORI
    {
        public int ALT_KATEGORI_REFNO { get; set; }
        public Nullable<int> KATEGORI_REFNO { get; set; }
        public string ALT_KATEGORI_ADI { get; set; }
    
        public virtual KATEGORI KATEGORI { get; set; }
    }
}
