//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_OGRENIYORUM
{
    using System;
    using System.Collections.Generic;
    
    public partial class FATURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FATURA()
        {
            this.FAT_DETAY = new HashSet<FAT_DETAY>();
        }
    
        public int FATURA_REFNO { get; set; }
        public Nullable<int> MUSTERI_REFNO { get; set; }
        public string FATURA_TIPI { get; set; }
        public Nullable<System.DateTime> FATURA_TARIHI { get; set; }
        public string ADRES { get; set; }
        public string SEHIR { get; set; }
        public string ILGILI_KISI { get; set; }
        public string ACIKLAMA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAT_DETAY> FAT_DETAY { get; set; }
        public virtual MUSTERI MUSTERI { get; set; }
    }
}
