//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_OGRENIYORUM
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KULLANICI()
        {
            this.YETKIs = new HashSet<YETKI>();
        }
    
        public int KULLANICI_REFNO { get; set; }
        public string KULLANICI_ADI { get; set; }
        public string SIFRESI { get; set; }
        public string DURUMU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YETKI> YETKIs { get; set; }
    }
}
