//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_OGRENIYORUM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUSTERI
    {
        public int MUSTERI_REFNO { get; set; }
        public string UNVANI { get; set; }
        public string ILGILI_KISI { get; set; }
        public string ADRES { get; set; }
        public string SEHIR { get; set; }
        public string POSTA_KODU { get; set; }
        public string TELEFON1 { get; set; }
        public string TELEFON2 { get; set; }
        public string TELEFON3 { get; set; }
        public string FAX { get; set; }
        public string E_POSTA { get; set; }
        public string WEB_ADRESI { get; set; }
        public string ACIKLAMA { get; set; }
        public string TIPI { get; set; }
        public Nullable<decimal> BORC { get; set; }
        public Nullable<decimal> ALACAK { get; set; }
        public Nullable<decimal> BAKIYE { get; set; }
        public string VERGI_DAIRESI { get; set; }
        public string VERGI_NUMARASI { get; set; }
    }
}
