//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_OGRENIYORUM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUSTERI_HAREKET
    {
        public int MUSTERI_HAREKET_REFNO { get; set; }
        public Nullable<int> MUSTERI_REFNO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<decimal> BORC { get; set; }
        public Nullable<decimal> ALACAK { get; set; }
        public string KAYNAK { get; set; }
        public Nullable<int> KAYNAK_REFNO { get; set; }
    }
}
