//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_OGRENIYORUM
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public URUN()
        {
            this.SIP_DETAY = new HashSet<SIP_DETAY>();
            this.FAT_DETAY = new HashSet<FAT_DETAY>();
            this.URUN_HAREKET = new HashSet<URUN_HAREKET>();
        }
    
        public int URUN_REFNO { get; set; }
        public string ADI { get; set; }
        public Nullable<int> KATEGORI_REFNO { get; set; }
        public Nullable<int> ALT_KATEGORI_REFNO { get; set; }
        public Nullable<int> TEDARIKCI_REFNO { get; set; }
        public Nullable<decimal> KDVSIZ_SATIS_FIYATI { get; set; }
        public Nullable<decimal> KDVSIZ_ALIS_FIYATI { get; set; }
        public Nullable<int> SATIS_KDV_ORANI { get; set; }
        public Nullable<int> ALIS_KDV_ORANI { get; set; }
        public string BARKODU { get; set; }
        public string BIRIM1 { get; set; }
        public string BIRIM2 { get; set; }
    
        public virtual KATEGORI KATEGORI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIP_DETAY> SIP_DETAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAT_DETAY> FAT_DETAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<URUN_HAREKET> URUN_HAREKET { get; set; }
    }
}
