//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_OGRENIYORUM
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUN
    {
        public int URUN_REFNO { get; set; }
        public string ADI { get; set; }
        public Nullable<int> KATEGORI_REFNO { get; set; }
        public Nullable<int> ALT_KATEGORI_REFNO { get; set; }
        public Nullable<int> TEDARIKCI_REFNO { get; set; }
        public Nullable<decimal> KDVSIZ_SATIS_FIYATI { get; set; }
        public Nullable<decimal> KDVSIZ_ALIS_FIYATI { get; set; }
        public Nullable<int> SATIS_KDV_ORANI { get; set; }
        public Nullable<int> ALIS_KDV_ORANI { get; set; }
        public string BARKODU { get; set; }
        public string BIRIM1 { get; set; }
        public string BIRIM2 { get; set; }
    
        public virtual KATEGORI KATEGORI { get; set; }
    }
}
