//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_OGRENIYORUM
{
    using System;
    using System.Collections.Generic;
    
    public partial class YETKI
    {
        public int YETKI_REFNO { get; set; }
        public Nullable<int> KULLANICI_REFNO { get; set; }
        public Nullable<int> MODUL_REFNO { get; set; }
        public Nullable<bool> EKLE { get; set; }
        public Nullable<bool> GUNCELLE { get; set; }
        public Nullable<bool> SIL { get; set; }
        public Nullable<bool> OKU { get; set; }
    }
}
