//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MARKA", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MARKA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MARKA_REFNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MARKA_ADIField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MARKA_REFNO {
            get {
                return this.MARKA_REFNOField;
            }
            set {
                if ((this.MARKA_REFNOField.Equals(value) != true)) {
                    this.MARKA_REFNOField = value;
                    this.RaisePropertyChanged("MARKA_REFNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MARKA_ADI {
            get {
                return this.MARKA_ADIField;
            }
            set {
                if ((object.ReferenceEquals(this.MARKA_ADIField, value) != true)) {
                    this.MARKA_ADIField = value;
                    this.RaisePropertyChanged("MARKA_ADI");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WSMARKASoap")]
    public interface WSMARKASoap {
        
        // CODEGEN: http://tempuri.org/ ad alanındaki kullaniciadi öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GirisYap", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.GirisYapResponse GirisYap(WindowsFormsApp1.ServiceReference1.GirisYapRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GirisYap", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.GirisYapResponse> GirisYapAsync(WindowsFormsApp1.ServiceReference1.GirisYapRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki arama öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMARKA", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.GetAllMARKAResponse GetAllMARKA(WindowsFormsApp1.ServiceReference1.GetAllMARKARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMARKA", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.GetAllMARKAResponse> GetAllMARKAAsync(WindowsFormsApp1.ServiceReference1.GetAllMARKARequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GirisYapRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GirisYap", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.GirisYapRequestBody Body;
        
        public GirisYapRequest() {
        }
        
        public GirisYapRequest(WindowsFormsApp1.ServiceReference1.GirisYapRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GirisYapRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string kullaniciadi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string parola;
        
        public GirisYapRequestBody() {
        }
        
        public GirisYapRequestBody(string kullaniciadi, string parola) {
            this.kullaniciadi = kullaniciadi;
            this.parola = parola;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GirisYapResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GirisYapResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.GirisYapResponseBody Body;
        
        public GirisYapResponse() {
        }
        
        public GirisYapResponse(WindowsFormsApp1.ServiceReference1.GirisYapResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GirisYapResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GirisYapResult;
        
        public GirisYapResponseBody() {
        }
        
        public GirisYapResponseBody(bool GirisYapResult) {
            this.GirisYapResult = GirisYapResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMARKARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMARKA", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.GetAllMARKARequestBody Body;
        
        public GetAllMARKARequest() {
        }
        
        public GetAllMARKARequest(WindowsFormsApp1.ServiceReference1.GetAllMARKARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllMARKARequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arama;
        
        public GetAllMARKARequestBody() {
        }
        
        public GetAllMARKARequestBody(string arama) {
            this.arama = arama;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMARKAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMARKAResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.GetAllMARKAResponseBody Body;
        
        public GetAllMARKAResponse() {
        }
        
        public GetAllMARKAResponse(WindowsFormsApp1.ServiceReference1.GetAllMARKAResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllMARKAResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceReference1.MARKA[] GetAllMARKAResult;
        
        public GetAllMARKAResponseBody() {
        }
        
        public GetAllMARKAResponseBody(WindowsFormsApp1.ServiceReference1.MARKA[] GetAllMARKAResult) {
            this.GetAllMARKAResult = GetAllMARKAResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSMARKASoapChannel : WindowsFormsApp1.ServiceReference1.WSMARKASoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSMARKASoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.WSMARKASoap>, WindowsFormsApp1.ServiceReference1.WSMARKASoap {
        
        public WSMARKASoapClient() {
        }
        
        public WSMARKASoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSMARKASoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSMARKASoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSMARKASoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.GirisYapResponse WindowsFormsApp1.ServiceReference1.WSMARKASoap.GirisYap(WindowsFormsApp1.ServiceReference1.GirisYapRequest request) {
            return base.Channel.GirisYap(request);
        }
        
        public bool GirisYap(string kullaniciadi, string parola) {
            WindowsFormsApp1.ServiceReference1.GirisYapRequest inValue = new WindowsFormsApp1.ServiceReference1.GirisYapRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.GirisYapRequestBody();
            inValue.Body.kullaniciadi = kullaniciadi;
            inValue.Body.parola = parola;
            WindowsFormsApp1.ServiceReference1.GirisYapResponse retVal = ((WindowsFormsApp1.ServiceReference1.WSMARKASoap)(this)).GirisYap(inValue);
            return retVal.Body.GirisYapResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.GirisYapResponse> WindowsFormsApp1.ServiceReference1.WSMARKASoap.GirisYapAsync(WindowsFormsApp1.ServiceReference1.GirisYapRequest request) {
            return base.Channel.GirisYapAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.GirisYapResponse> GirisYapAsync(string kullaniciadi, string parola) {
            WindowsFormsApp1.ServiceReference1.GirisYapRequest inValue = new WindowsFormsApp1.ServiceReference1.GirisYapRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.GirisYapRequestBody();
            inValue.Body.kullaniciadi = kullaniciadi;
            inValue.Body.parola = parola;
            return ((WindowsFormsApp1.ServiceReference1.WSMARKASoap)(this)).GirisYapAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.GetAllMARKAResponse WindowsFormsApp1.ServiceReference1.WSMARKASoap.GetAllMARKA(WindowsFormsApp1.ServiceReference1.GetAllMARKARequest request) {
            return base.Channel.GetAllMARKA(request);
        }
        
        public WindowsFormsApp1.ServiceReference1.MARKA[] GetAllMARKA(string arama) {
            WindowsFormsApp1.ServiceReference1.GetAllMARKARequest inValue = new WindowsFormsApp1.ServiceReference1.GetAllMARKARequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.GetAllMARKARequestBody();
            inValue.Body.arama = arama;
            WindowsFormsApp1.ServiceReference1.GetAllMARKAResponse retVal = ((WindowsFormsApp1.ServiceReference1.WSMARKASoap)(this)).GetAllMARKA(inValue);
            return retVal.Body.GetAllMARKAResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.GetAllMARKAResponse> WindowsFormsApp1.ServiceReference1.WSMARKASoap.GetAllMARKAAsync(WindowsFormsApp1.ServiceReference1.GetAllMARKARequest request) {
            return base.Channel.GetAllMARKAAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.GetAllMARKAResponse> GetAllMARKAAsync(string arama) {
            WindowsFormsApp1.ServiceReference1.GetAllMARKARequest inValue = new WindowsFormsApp1.ServiceReference1.GetAllMARKARequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.GetAllMARKARequestBody();
            inValue.Body.arama = arama;
            return ((WindowsFormsApp1.ServiceReference1.WSMARKASoap)(this)).GetAllMARKAAsync(inValue);
        }
    }
}
